{{- if .Values.objectStorage.enable -}}
apiVersion: ceph.rook.io/v1
kind: CephObjectStore
metadata:
  name: ocs-storagecluster-cephobjectstore
  namespace: openshift-storage
spec:
  dataPool:
    erasureCoded:
      codingChunks: 0
      dataChunks: 0
    failureDomain: zone
    replicated:
      size: {{ .Values.objectStorage.dataPool.replicas | default 3 }}
  gateway:
    #allNodes: false
    instances: {{ .Values.objectStorage.gateway.instances | default 1 }}
    placement:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: cluster.ocs.openshift.io/openshift-storage
              operator: Exists
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - podAffinityTerm:
            labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - rook-ceph-rgw
            topologyKey: kubernetes.io/hostname
          weight: 100
      tolerations:
      - effect: NoSchedule
        key: node.ocs.openshift.io/storage
        operator: Equal
        value: "true"
    port: 80
    resources:
      requests:
        cpu: {{ .Values.objectStorage.resources.requests.cpu | squote }}
        memory: {{ .Values.objectStorage.resources.requests.memory | squote }}
      limits:
        cpu: {{ .Values.objectStorage.resources.limits.cpu | squote }}
        memory: {{ .Values.objectStorage.resources.limits.memory | squote }}
  metadataPool:
    erasureCoded:
      codingChunks: 0
      dataChunks: 0
    failureDomain: zone
    replicated:
      size: 3
{{- end -}}
